### PR TITLE
bistro_script.ml: fix build with ppxlib 0.23

### LINKED ISSUE #47: build failure due to ppxlib 0.23 incompatibility
Upstreaming this from Nixpkgs:

```
# File "ppx/bistro_script.ml", line 201, characters 18-41:
# 201 |           let e = Parser.parse_expression Lexer.token (Lexing.from_string txt) in
#                         ^^^^^^^^^^^^^^^^^^^^^^^
# Alert deprecated: module Ppxlib.Parser
# Accessing this module directly is deprecated, use Ocaml_common.Parser instead
# File "ppx/bistro_script.ml", line 201, characters 18-41:
# 201 |           let e = Parser.parse_expression Lexer.token (Lexing.from_string txt) in
#                         ^^^^^^^^^^^^^^^^^^^^^^^
# Error: Unbound value Parser.parse_expression
```

Indeed Nixpkgs simply patches `Parser.parse_expression` to `Ocaml_common.Parser.parse_expression` here.

### PR DESCRIPTION
**Pull request by bcdarwin**
Fixes #47.

### CODE REVIEW

**Comment by pveber** [comment]
Thanks for the PR, unfortunately the fix doesn't compile. I pushed a somewhat similar modification (b82548b). Thanks again!
